### ISSUE TITLE
Implement new DOSDP batch mode in ODK

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#306]
I need to review the following tickets and their implementation:

- [x] [Feature request: Make dosdp query take a list of patterns as input](https://github.com/INCATools/dosdp-tools/issues/120)
- [x] [Add are more meaningful message when TSV does not contain correctly named column](https://github.com/INCATools/dosdp-tools/issues/64)
- [x] [Cant use owl Thing IRI in TSV](https://github.com/INCATools/dosdp-tools/issues/154)
- [x] [Feature request: Do not make annotation assertions when empty table cell](https://github.com/INCATools/dosdp-tools/issues/128)
- [x] [Question: making data_vars related columns optional?](https://github.com/INCATools/dosdp-tools/issues/137)

Pulls:
- [x] [Batch mode for generating multiple patterns at once](https://github.com/INCATools/dosdp-tools/pull/187)
- [x] [Handle missing columns and empty table cells by omitting outputs which require those values](https://github.com/INCATools/dosdp-tools/pull/185)

**Comment by balhoff** [comment]
@matentzn here is a beta release for testing these features: https://github.com/INCATools/dosdp-tools/releases/tag/v0.14-beta.1

**Comment by balhoff** [comment]
@matentzn here is new beta: https://github.com/INCATools/dosdp-tools/releases/tag/v0.14-beta.2

Please test specification of input/output directories, and batch query. I changed the batch patterns input parameter to `--batch-patterns`.

**Comment by matentzn** [comment]
Testing pipeline:

- [ ] Compile into ODK dev
- [ ]  Run on FBBT, MAXO and WBP to ensure that existing pipelines continue to work.
- [ ] Create one test case for each of the new features above
- [ ] Feedback to Jim, who can then make a proper release
- [ ] Add into ODK release
- [ ] Write release notes and show to Erik and Sofia how new features work

**Comment by matentzn** [comment]
Wait for:

- [ ] https://github.com/INCATools/dosdp-tools/issues/199

**Comment by balhoff** [comment]
@matentzn new dosdp-tools beta: https://github.com/INCATools/dosdp-tools/releases/tag/v0.14-beta.3

**Comment by matentzn** [comment]
Ok thanks a lot! first three tests pass, give me a week or so to make sure its all in order.

**Comment by matentzn** [comment]
https://github.com/INCATools/dosdp-tools/issues/120

**Comment by matentzn** [comment]
@balhoff minus this tiny issue above, its great! Ready to be released!

I will work it into ODK asap. Thanks!

**Comment by balhoff** [comment]
Released: https://github.com/INCATools/dosdp-tools/releases/tag/v0.14

**Comment by matentzn** [comment]
Awesome! Thanks @balhoff .

**Comment by matentzn** [comment]
Fixed in https://github.com/INCATools/ontology-development-kit/pull/318
